# Generated by Django 5.2.17 on 2026-09-26 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Politique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="Version publiée (v1, v2…)", max_length=16
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        blank=True, choices=[("Publiée", "Publiee")], max_length=16
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Date de publication", null=True
                    ),
                ),
                ("signataire", models.CharField(blank=True, max_length=255)),
                (
                    "resume",
                    models.TextField(
                        blank=True, help_text="Résumé généré à partir des orientations"
                    ),
                ),
                (
                    "orientations",
                    models.TextField(
                        blank=True, help_text="Orientations, une par ligne"
                    ),
                ),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "politique SM",
                "verbose_name_plural": "politiques SM",
            },
        ),
        migrations.CreateModel(
            name="Accuse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "collaborateur",
                    models.CharField(
                        help_text="Collaborateur (nom complet)", max_length=255
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        default="—",
                        help_text="Date de lecture (AAAA-MM-JJ) ou '—'",
                        max_length=16,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("Lu", "Lu"), ("Non lu", "Non Lu")],
                        default="Non lu",
                        max_length=8,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "accusé de lecture",
                "verbose_name_plural": "accusés de lecture",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="leadership_accuse_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChampPerso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("libelle", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Document", "Document"),
                            ("Texte", "Texte"),
                            ("Date", "Date"),
                            ("Nombre", "Nombre"),
                        ],
                        max_length=16,
                    ),
                ),
                ("valeur", models.TextField(help_text="Valeur ou nom du document")),
                ("commentaire", models.TextField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "champ personnalisé",
                "verbose_name_plural": "champs personnalisés",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="leadership_champperso_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Diffusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "d",
                    models.CharField(
                        help_text="Horodatage (AAAA-MM-JJ HH:MM)", max_length=32
                    ),
                ),
                (
                    "u",
                    models.CharField(
                        help_text="Auteur de la diffusion (nom complet)", max_length=255
                    ),
                ),
                (
                    "doc",
                    models.CharField(
                        help_text="Document diffusé (ex. « Politique SM v3 »)",
                        max_length=255,
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            (
                                "interne",
                                "Interne — dépôt direct dans l'espace du destinataire",
                            ),
                            ("externe", "Externe — envoi par email avec pièce jointe"),
                        ],
                        default="interne",
                        max_length=8,
                    ),
                ),
                ("destinataires", models.CharField(max_length=255)),
                (
                    "piece",
                    models.CharField(
                        default="—",
                        help_text="Pièce jointe (obligatoire en externe)",
                        max_length=255,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="leadership_diffusion_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MembreComite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("date_naissance", models.DateField(help_text="Date de naissance")),
                (
                    "role",
                    models.CharField(
                        help_text="Rôle au sein du comité", max_length=255
                    ),
                ),
                ("mandat_fin", models.DateField(help_text="Fin de mandat")),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "membre du comité hygiène et santé",
                "verbose_name_plural": "comité hygiène et santé",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="leadership_membrecomite_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanStrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("version", models.CharField(max_length=16)),
                (
                    "titre",
                    models.CharField(help_text="Titre du document", max_length=255),
                ),
                (
                    "fichier",
                    models.CharField(
                        help_text="Document (PDF ou Word) — nom de fichier",
                        max_length=255,
                    ),
                ),
                ("date_validation", models.DateField(help_text="Date de validation")),
                (
                    "valide_par",
                    models.CharField(help_text="Validé par", max_length=255),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("En vigueur", "En Vigueur"),
                            ("Obsolète", "Obsolete"),
                        ],
                        default="En vigueur",
                        max_length=16,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "plan stratégique",
                "verbose_name_plural": "plans stratégiques",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="leadership_planstrat_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Poste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "intitule",
                    models.CharField(help_text="Intitulé du poste", max_length=255),
                ),
                (
                    "direction",
                    models.CharField(help_text="Direction ou service", max_length=255),
                ),
                (
                    "titulaire",
                    models.CharField(
                        blank=True, help_text="Titulaire (nom complet)", max_length=255
                    ),
                ),
                ("mission", models.TextField()),
                (
                    "responsabilites",
                    models.TextField(help_text="Responsabilités liées au SM"),
                ),
                (
                    "processus",
                    models.JSONField(
                        blank=True, default=list, help_text="Processus concernés (id)"
                    ),
                ),
                (
                    "preuve",
                    models.CharField(
                        help_text="Preuve de communication de l'évolution",
                        max_length=255,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "fiche de poste",
                "verbose_name_plural": "fiches de poste",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"), name="leadership_poste_uid_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PreuveCom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "objet",
                    models.CharField(help_text="Objet communiqué", max_length=255),
                ),
                ("date", models.DateField()),
                (
                    "support",
                    models.CharField(
                        choices=[
                            ("Affichage", "Affichage"),
                            ("Réunion", "Reunion"),
                            ("Email", "Email"),
                            ("Intranet", "Intranet"),
                            ("Causerie", "Causerie"),
                        ],
                        max_length=16,
                    ),
                ),
                ("lieu", models.CharField(help_text="Lieu ou canal", max_length=255)),
                (
                    "personnes",
                    models.PositiveIntegerField(help_text="Personnes touchées"),
                ),
                (
                    "preuve",
                    models.CharField(
                        help_text="Preuve jointe — nom de fichier", max_length=255
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "preuve de communication",
                "verbose_name_plural": "preuves de communication",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="leadership_preuvecom_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Representant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("fonction", models.CharField(max_length=255)),
                ("mandat_debut", models.DateField(help_text="Début de mandat")),
                ("mandat_fin", models.DateField(help_text="Fin de mandat")),
                (
                    "statut",
                    models.CharField(
                        choices=[("Actif", "Actif"), ("Révoqué", "Revoque")],
                        default="Actif",
                        help_text="État",
                        max_length=16,
                    ),
                ),
                (
                    "suppleant",
                    models.CharField(
                        blank=True,
                        help_text="Délégué suppléant (le cas échéant)",
                        max_length=255,
                    ),
                ),
                (
                    "qualite_lien",
                    models.CharField(
                        choices=[
                            ("Titulaire", "Titulaire"),
                            ("Suppléant", "Suppleant"),
                            ("Représentant syndical", "Syndical"),
                            ("Invité permanent", "Invite"),
                        ],
                        default="Titulaire",
                        help_text="Qualité du lien",
                        max_length=32,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "représentant des travailleurs",
                "verbose_name_plural": "représentants des travailleurs",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="leadership_representant_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Reunion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "date",
                    models.DateField(blank=True, help_text="Date de tenue", null=True),
                ),
                (
                    "objet",
                    models.CharField(help_text="Objet de la réunion", max_length=255),
                ),
                (
                    "participants",
                    models.CharField(
                        choices=[
                            ("Comité HS (CHSS)", "Chss"),
                            ("Délégués du personnel", "Delegues"),
                            ("Tout le personnel", "Personnel"),
                        ],
                        default="Comité HS (CHSS)",
                        max_length=32,
                    ),
                ),
                ("compte_rendu", models.TextField(blank=True)),
                (
                    "plan_action",
                    models.TextField(
                        blank=True,
                        help_text="Plan d'action de suivi (action, responsable, échéance)",
                    ),
                ),
                (
                    "statut_plan",
                    models.CharField(
                        choices=[
                            ("À faire", "A Faire"),
                            ("En cours", "En Cours"),
                            ("Clôturé", "Cloture"),
                        ],
                        default="À faire",
                        max_length=16,
                    ),
                ),
                ("date_prevue", models.DateField(help_text="Date prévue")),
                (
                    "statut",
                    models.CharField(
                        choices=[("Planifiée", "Planifiee"), ("Réalisée", "Realisee")],
                        default="Planifiée",
                        max_length=16,
                    ),
                ),
                ("ordre_du_jour", models.TextField(help_text="Ordre du jour")),
                (
                    "preuve1",
                    models.CharField(
                        blank=True,
                        help_text="Preuve 1 (PV, feuille de présence…)",
                        max_length=255,
                    ),
                ),
                (
                    "preuve2",
                    models.CharField(blank=True, help_text="Preuve 2", max_length=255),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "réunion de consultation",
                "verbose_name_plural": "réunions de consultation",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="leadership_reunion_uid_uniq",
                    )
                ],
            },
        ),
    ]
