# Generated by Django 5.2.17 on 2026-09-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadership", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accuse",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="champperso",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="diffusion",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="membrecomite",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="planstrat",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="poste",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="preuvecom",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="representant",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="reunion",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
