# Generated by Django 5.2.17 on 2026-09-26 21:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloturesAn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "labels",
                    models.JSONField(
                        blank=True, default=list, help_text="Libellés des périodes"
                    ),
                ),
                (
                    "clotures",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Actions clôturées par période",
                    ),
                ),
                (
                    "ouvertures",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Actions ouvertes par période",
                    ),
                ),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "clôtures annuelles",
                "verbose_name_plural": "clôtures annuelles",
            },
        ),
        migrations.CreateModel(
            name="CloturesMois",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "labels",
                    models.JSONField(
                        blank=True, default=list, help_text="Libellés des périodes"
                    ),
                ),
                (
                    "clotures",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Actions clôturées par période",
                    ),
                ),
                (
                    "ouvertures",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Actions ouvertes par période",
                    ),
                ),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "clôtures mensuelles",
                "verbose_name_plural": "clôtures mensuelles",
            },
        ),
        migrations.CreateModel(
            name="ExigenceNormative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "norme",
                    models.CharField(
                        choices=[
                            ("9001", "Iso 9001"),
                            ("14001", "Iso 14001"),
                            ("45001", "Iso 45001"),
                            ("27001", "Iso 27001"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Version de la norme (2015, 2018…)",
                        max_length=16,
                    ),
                ),
                (
                    "article",
                    models.CharField(help_text="Article (4.1, A.8…)", max_length=32),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text="Intitulé de l'exigence", max_length=255
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        help_text="Module du noyau (1.1 Enjeux…)",
                        max_length=128,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Commune", "Commune"), ("Spécifique", "Specifique")],
                        default="Commune",
                        max_length=16,
                    ),
                ),
                ("preuve", models.TextField(blank=True, help_text="Preuve attendue")),
                (
                    "couverture",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Couverture démontrée (0 à 100 %)",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "exigence normative",
                "verbose_name_plural": "couverture normative",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="pilotage_exigencenormative_uid_uniq",
                    )
                ],
            },
        ),
    ]
