# Generated by Django 5.2.17 on 2026-09-27 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Recevoir le récapitulatif quotidien par e-mail",
                    ),
                ),
                (
                    "echeances",
                    models.BooleanField(
                        default=True,
                        help_text="Inclure les échéances dépassées ou proches",
                    ),
                ),
                (
                    "validations",
                    models.BooleanField(
                        default=True, help_text="Inclure les validations en attente"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "préférence de notification",
                "verbose_name_plural": "préférences de notification",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Jour de référence de l'envoi")),
                (
                    "key",
                    models.CharField(
                        help_text="Empreinte de l'alerte (type, titre, détail)",
                        max_length=64,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("alerte", "Alerte"), ("validation", "Validation")],
                        max_length=16,
                    ),
                ),
                ("titre", models.CharField(blank=True, max_length=255)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification envoyée",
                "verbose_name_plural": "notifications envoyées",
                "ordering": ["-sent_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date", "key"),
                        name="notifications_log_uniq_per_day",
                    )
                ],
            },
        ),
    ]
