# Generated by Django 5.2.17 on 2026-09-26 21:33

import apps.operations.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "ref",
                    models.CharField(
                        help_text="Référence (ex. PR-QSE-01)", max_length=64
                    ),
                ),
                ("intitule", models.CharField(help_text="Intitulé", max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Procédure", "Procédure"),
                            ("Instruction", "Instruction"),
                            ("Formulaire", "Formulaire"),
                            ("Enregistrement", "Enregistrement"),
                            ("Politique", "Politique"),
                            ("Manuel", "Manuel"),
                            ("Document externe", "Document externe"),
                        ],
                        default="Procédure",
                        max_length=32,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1",
                        help_text="Version en vigueur (dernière approuvée)",
                        max_length=16,
                    ),
                ),
                (
                    "proprietaire",
                    models.CharField(
                        blank=True,
                        help_text="Propriétaire (nom complet)",
                        max_length=255,
                    ),
                ),
                (
                    "processus",
                    models.CharField(
                        blank=True, help_text="Processus (id)", max_length=32
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Rédaction", "Rédaction"),
                            ("Vérification", "Vérification"),
                            ("Approbation", "Approbation"),
                            ("Diffusé", "Diffusé"),
                            ("Refusé", "Refusé"),
                            ("Obsolète", "Obsolète"),
                        ],
                        default="Rédaction",
                        max_length=16,
                    ),
                ),
                (
                    "date_creation",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="Date de création",
                    ),
                ),
                ("date_revue", models.DateField(help_text="Date de prochaine revue")),
                (
                    "date_version",
                    models.DateField(
                        blank=True, help_text="Date de la version", null=True
                    ),
                ),
                (
                    "droits",
                    models.TextField(
                        blank=True,
                        help_text="Droits d'accès (lecture, modification, validation)",
                    ),
                ),
                (
                    "diffusion",
                    models.TextField(blank=True, help_text="Liste de diffusion"),
                ),
                (
                    "versions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Historique des versions : [{v, date, auteur, contenu}], la dernière en fin",
                    ),
                ),
                (
                    "redacteur",
                    models.CharField(
                        blank=True, help_text="Rédacteur (nom complet)", max_length=255
                    ),
                ),
                (
                    "approbateur",
                    models.CharField(
                        blank=True,
                        help_text="Approbateur désigné (nom complet)",
                        max_length=255,
                    ),
                ),
                (
                    "refus",
                    models.TextField(
                        blank=True,
                        help_text="Motif du dernier refus (renvoyé à l'auteur)",
                        null=True,
                    ),
                ),
                (
                    "accuses",
                    models.PositiveIntegerField(
                        blank=True, help_text="Accusés de lecture reçus", null=True
                    ),
                ),
                (
                    "modele",
                    models.CharField(
                        blank=True,
                        help_text="Modèle utilisé (nom)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        help_text="Pièce jointe (fichier)",
                        max_length=500,
                        null=True,
                        upload_to=apps.operations.models.document_upload_to,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents (GED)",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="operations_document_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Modele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("nom", models.CharField(help_text="Nom du modèle", max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Procédure", "Procédure"),
                            ("Instruction", "Instruction"),
                            ("Formulaire", "Formulaire"),
                            ("Enregistrement", "Enregistrement"),
                            ("Politique", "Politique"),
                            ("Manuel", "Manuel"),
                            ("Document externe", "Document externe"),
                        ],
                        help_text="Type de document produit",
                        max_length=32,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Structure du modèle"),
                ),
                (
                    "processus",
                    models.CharField(
                        default="Tous",
                        help_text="Processus (id) ou « Tous »",
                        max_length=32,
                    ),
                ),
                (
                    "fichier",
                    models.CharField(
                        blank=True,
                        help_text="Fichier du modèle (nom)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "modèle de document",
                "verbose_name_plural": "modèles de documents",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="operations_modele_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanOps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "processus",
                    models.CharField(
                        blank=True, help_text="Processus (id)", max_length=32
                    ),
                ),
                ("plan", models.TextField(help_text="Plan d'action")),
                (
                    "responsable",
                    models.CharField(
                        blank=True,
                        help_text="Responsable unique (nom complet)",
                        max_length=255,
                    ),
                ),
                ("echeance", models.DateField(help_text="Échéance")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Pas fait", "Pas fait"),
                            ("En cours", "En cours"),
                            ("Fait", "Fait"),
                        ],
                        default="Pas fait",
                        max_length=16,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "plan d'action opérationnel",
                "verbose_name_plural": "plans d'action opérationnels",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="operations_planops_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Urgence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "type",
                    models.CharField(
                        help_text="Type de situation d'urgence", max_length=255
                    ),
                ),
                (
                    "procedure",
                    models.CharField(
                        blank=True, help_text="Procédure de référence", max_length=255
                    ),
                ),
                ("consignes", models.TextField(blank=True, help_text="Consignes")),
                ("moyens", models.TextField(blank=True, help_text="Moyens de secours")),
                (
                    "responsables",
                    models.CharField(
                        blank=True,
                        help_text="Responsables (texte libre)",
                        max_length=500,
                    ),
                ),
                (
                    "risques",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Risques associés (id, module 3)",
                    ),
                ),
                (
                    "sites",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sites d'application (noms, module 1.3)",
                    ),
                ),
                (
                    "exercices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Exercices : [{date, participants, scenario, procedure, statut, compteRendu, actions}]",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "situation d'urgence",
                "verbose_name_plural": "situations d'urgence",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="operations_urgence_uid_uniq",
                    )
                ],
            },
        ),
    ]
