# Generated by Django 5.2.17 on 2026-09-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="modele",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="planops",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="urgence",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
