# Generated by Django 5.2.17 on 2026-09-26 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Declaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "texte",
                    models.CharField(
                        blank=True,
                        help_text="Texte concerné (id de db.textes)",
                        max_length=32,
                    ),
                ),
                (
                    "objet",
                    models.CharField(help_text="Objet de l'écart", max_length=500),
                ),
                ("cause", models.TextField(help_text="Cause de l'écart")),
                ("impact", models.TextField(help_text="Impact de l'écart")),
                (
                    "plan_action",
                    models.TextField(help_text="Plan d'action de mise en conformité"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("Soumise", "Soumise"),
                            ("Validée", "Validee"),
                            ("Refusée", "Refusee"),
                        ],
                        default="Brouillon",
                        max_length=16,
                    ),
                ),
                (
                    "auteur",
                    models.CharField(
                        blank=True, help_text="Auteur (nom complet)", max_length=255
                    ),
                ),
                ("date", models.DateField(help_text="Date de la déclaration")),
                (
                    "commentaire_dg",
                    models.CharField(
                        blank=True,
                        help_text="Décision ou commentaire du Directeur Général",
                        max_length=500,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "déclaration d'écart réglementaire",
                "verbose_name_plural": "déclarations d'écart réglementaire",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="planification_declaration_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FicheMaitrise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "objet",
                    models.CharField(
                        help_text="Processus ou activité à risque", max_length=255
                    ),
                ),
                (
                    "processus",
                    models.CharField(
                        blank=True,
                        help_text="Processus lié (id de db.processus)",
                        max_length=32,
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True,
                        help_text="Responsable (nom complet)",
                        max_length=255,
                    ),
                ),
                ("criteres", models.TextField(help_text="Critères opérationnels")),
                ("moyens", models.TextField(help_text="Moyens de maîtrise")),
                (
                    "ressources",
                    models.CharField(help_text="Ressources associées", max_length=500),
                ),
                (
                    "risques",
                    models.JSONField(
                        default=list, help_text="Risques identifiés (id de db.risques)"
                    ),
                ),
                (
                    "derniere_maj",
                    models.DateField(help_text="Date de la dernière mise à jour"),
                ),
                (
                    "prochaine_maj",
                    models.DateField(help_text="Date de la prochaine mise à jour"),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "fiche de maîtrise opérationnelle",
                "verbose_name_plural": "fiches de maîtrise opérationnelle",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="planification_fichemaitrise_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Objectif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "code",
                    models.CharField(
                        help_text="Code de l'objectif (OB-01…)", max_length=32
                    ),
                ),
                (
                    "libelle",
                    models.CharField(help_text="Énoncé de l'objectif", max_length=500),
                ),
                (
                    "axe",
                    models.CharField(
                        blank=True,
                        help_text="Orientation stratégique du module 2 (id de db.axes)",
                        max_length=32,
                    ),
                ),
                (
                    "kpi",
                    models.CharField(
                        help_text="Indicateur de mesure (KPI)", max_length=255
                    ),
                ),
                (
                    "cible",
                    models.CharField(
                        help_text="Valeur cible de l'indicateur", max_length=255
                    ),
                ),
                ("delai", models.DateField(help_text="Délai d'atteinte de l'objectif")),
                (
                    "processus",
                    models.JSONField(
                        default=list,
                        help_text="Processus concernés (id de db.processus)",
                    ),
                ),
                (
                    "efficacite",
                    models.CharField(
                        choices=[
                            ("Non évaluée", "Non Evaluee"),
                            ("En cours d'évaluation", "En Cours"),
                            ("Partiellement efficace", "Partiellement"),
                            ("Efficace", "Efficace"),
                            ("Non efficace", "Non Efficace"),
                        ],
                        default="Non évaluée",
                        help_text="Évaluation de l'efficacité",
                        max_length=32,
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Plan d'action : [{libelle, responsable, echeance, statut, pieces?, observation}]",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "objectif",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="planification_objectif_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Opportunite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "intitule",
                    models.CharField(
                        help_text="Intitulé de l'opportunité", max_length=500
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Qualité", "Qualite"),
                            ("Environnement", "Environnement"),
                            ("SST", "Sst"),
                            ("Sécurité de l'information", "Securite Info"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        help_text="Origine (analyse PESTEL, enjeu…)", max_length=500
                    ),
                ),
                ("benefices", models.TextField(help_text="Bénéfices attendus")),
                (
                    "probabilite",
                    models.PositiveSmallIntegerField(
                        help_text="Probabilité de réalisation (1 à 4)"
                    ),
                ),
                (
                    "impact",
                    models.PositiveSmallIntegerField(
                        help_text="Niveau d'impact (1 à 4) ; niveau = probabilité × impact"
                    ),
                ),
                (
                    "exploitation",
                    models.CharField(
                        help_text="Moyen d'exploitation ou de valorisation",
                        max_length=500,
                    ),
                ),
                (
                    "processus",
                    models.JSONField(
                        default=list,
                        help_text="Processus associés (id de db.processus)",
                    ),
                ),
                (
                    "action",
                    models.CharField(help_text="Action générée", max_length=500),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True,
                        help_text="Responsable (nom complet)",
                        max_length=255,
                    ),
                ),
                ("echeance", models.DateField(help_text="Échéance de l'action")),
                (
                    "statut_action",
                    models.CharField(
                        choices=[
                            ("Mise en œuvre", "Mise En Oeuvre"),
                            ("En cours", "En Cours"),
                            ("Clôturé", "Cloture"),
                        ],
                        default="Mise en œuvre",
                        max_length=16,
                    ),
                ),
                (
                    "efficacite",
                    models.CharField(
                        choices=[
                            ("À évaluer", "A Evaluer"),
                            ("Efficace", "Efficace"),
                            ("Partiellement efficace", "Partiellement"),
                            ("Non efficace", "Non Efficace"),
                        ],
                        default="À évaluer",
                        max_length=32,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "opportunité",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="planification_opportunite_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RapportConformite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        help_text="Référence séquentielle (RC-2026-001…)",
                        max_length=32,
                    ),
                ),
                (
                    "texte",
                    models.CharField(
                        blank=True,
                        help_text="Texte concerné (id de db.textes)",
                        max_length=32,
                    ),
                ),
                (
                    "titre",
                    models.CharField(help_text="Intitulé du rapport", max_length=500),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Conforme", "Conforme"),
                            ("Non conforme", "Non Conforme"),
                            ("En cours", "En Cours"),
                        ],
                        help_text="Conclusion",
                        max_length=16,
                    ),
                ),
                ("date", models.DateField(help_text="Date du rapport")),
                (
                    "auteur",
                    models.CharField(
                        blank=True, help_text="Auteur (nom complet)", max_length=255
                    ),
                ),
                ("synthese", models.TextField(help_text="Synthèse")),
                (
                    "pieces",
                    models.CharField(help_text="Pièces jointes", max_length=255),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "rapport de conformité",
                "verbose_name_plural": "rapports de conformité",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="planification_rapportconformite_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Risque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "intitule",
                    models.CharField(help_text="Intitulé du risque", max_length=500),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Qualité", "Qualite"),
                            ("Environnement", "Environnement"),
                            ("SST", "Sst"),
                            ("Sécurité de l'information", "Securite Info"),
                            ("Situation d'urgence", "Urgence"),
                        ],
                        max_length=32,
                    ),
                ),
                ("cause", models.TextField(help_text="Cause")),
                ("consequences", models.TextField(help_text="Conséquences")),
                (
                    "probabilite",
                    models.PositiveSmallIntegerField(
                        help_text="Probabilité (1 rare à 4 fréquent)"
                    ),
                ),
                (
                    "criticite",
                    models.PositiveSmallIntegerField(
                        help_text="Criticité / gravité (1 mineure à 4 grave) ; niveau = probabilité × criticité"
                    ),
                ),
                (
                    "traitement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Éviter", "Eviter"),
                            ("Réduire", "Reduire"),
                            ("Transférer", "Transferer"),
                            ("Accepter", "Accepter"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "processus",
                    models.JSONField(
                        default=list,
                        help_text="Processus associés (id de db.processus)",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action de traitement générée", max_length=500
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True,
                        help_text="Responsable (nom complet)",
                        max_length=255,
                    ),
                ),
                (
                    "echeance",
                    models.DateField(
                        help_text="Échéance de l'action (ajoutée au planning)"
                    ),
                ),
                (
                    "statut_action",
                    models.CharField(
                        choices=[
                            ("Mise en œuvre", "Mise En Oeuvre"),
                            ("En cours", "En Cours"),
                            ("Clôturé", "Cloture"),
                        ],
                        default="Mise en œuvre",
                        max_length=16,
                    ),
                ),
                (
                    "efficacite",
                    models.CharField(
                        choices=[
                            ("À évaluer", "A Evaluer"),
                            ("Efficace", "Efficace"),
                            ("Partiellement efficace", "Partiellement"),
                            ("Non efficace", "Non Efficace"),
                        ],
                        default="À évaluer",
                        max_length=32,
                    ),
                ),
                (
                    "realise",
                    models.BooleanField(
                        default=False, help_text="Risque survenu (inscrit au registre)"
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "risque",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="planification_risque_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Texte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "intitule",
                    models.CharField(help_text="Intitulé du texte", max_length=500),
                ),
                (
                    "categorie",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Loi", "Loi"),
                            ("Décret", "Decret"),
                            ("Arrêté", "Arrete"),
                            ("Ordonnance", "Ordonnance"),
                            ("Convention", "Convention"),
                            ("Norme", "Norme"),
                            ("Autre", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "domaine",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Santé et sécurité au travail", "Sst"),
                            ("Environnement", "Environnement"),
                            ("Déchets", "Dechets"),
                            ("Protection des données", "Donnees"),
                            ("Social", "Social"),
                            ("Qualité et consommation", "Qualite"),
                            ("Fiscal", "Fiscal"),
                        ],
                        max_length=64,
                    ),
                ),
                ("date_publication", models.DateField(help_text="Date de publication")),
                (
                    "lien",
                    models.CharField(
                        help_text="Lien vers la source officielle", max_length=500
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("Fait", "Fait"), ("Pas fait", "Pas Fait")],
                        default="Pas fait",
                        help_text="Statut de conformité",
                        max_length=16,
                    ),
                ),
                (
                    "justificatif",
                    models.TextField(help_text="Justificatif du statut de conformité"),
                ),
                (
                    "pieces",
                    models.CharField(
                        help_text="Pièces justificatives (preuves d'audit)",
                        max_length=255,
                    ),
                ),
                (
                    "echeance",
                    models.DateField(
                        help_text="Date de la prochaine évaluation de conformité"
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True,
                        help_text="Responsable (nom complet)",
                        max_length=255,
                    ),
                ),
                (
                    "diffuse",
                    models.BooleanField(
                        blank=True, help_text="Texte diffusé aux intéressés", null=True
                    ),
                ),
                (
                    "statut_diff",
                    models.CharField(
                        blank=True,
                        help_text="Statut de diffusion (Diffusé)",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "destinataire_diff",
                    models.CharField(
                        blank=True,
                        help_text="Cible de la dernière diffusion",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "texte réglementaire",
                "verbose_name_plural": "textes réglementaires",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="planification_texte_uid_uniq",
                    )
                ],
            },
        ),
    ]
