# Generated by Django 5.2.17 on 2026-09-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declaration",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fichemaitrise",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="objectif",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="opportunite",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rapportconformite",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="risque",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="texte",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
