# Generated by Django 5.2.17 on 2026-09-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="droits_par_processus",
            field=models.BooleanField(default=False),
        ),
    ]
