# Generated by Django 5.2.17 on 2026-09-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Processus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                ("code", models.CharField(max_length=32)),
                ("intitule", models.CharField(max_length=255)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("Pilotage", "Pilotage"),
                            ("Réalisation", "Realisation"),
                            ("Support", "Support"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "proprietaire",
                    models.CharField(
                        blank=True, help_text="Pilote (nom complet)", max_length=255
                    ),
                ),
                (
                    "copilote",
                    models.JSONField(
                        blank=True, default=list, help_text="Copilotes (noms complets)"
                    ),
                ),
                ("finalite", models.TextField(blank=True)),
                ("entrees", models.TextField(blank=True)),
                ("sorties", models.TextField(blank=True)),
                ("indicateurs", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "processus",
                "ordering": ["position", "id"],
                "abstract": False,
            },
        ),
    ]
