# Generated by Django 5.2.17 on 2026-09-26 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contexte", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processus",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.organisation",
            ),
        ),
        migrations.AddConstraint(
            model_name="processus",
            constraint=models.UniqueConstraint(
                fields=("organisation", "uid"), name="contexte_processus_uid_uniq"
            ),
        ),
    ]
