# Generated by Django 5.2.17 on 2026-09-26 21:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexte", "0002_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Activité", "Activite"),
                            ("Processus", "Processus"),
                            ("Produit", "Produit"),
                            ("Service", "Service"),
                        ],
                        max_length=16,
                    ),
                ),
                ("libelle", models.CharField(max_length=255)),
                (
                    "site",
                    models.CharField(
                        blank=True,
                        help_text="Nom du site (db.sites[].nom)",
                        max_length=255,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("Inclus", "Inclus"), ("Exclu", "Exclu")],
                        help_text="Inclus ou exclu du domaine",
                        max_length=8,
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        help_text="Justification (au moins 10 caractères)"
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "activité couverte",
                "verbose_name_plural": "activités couvertes",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="contexte_activite_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AnalyseVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "version",
                    models.CharField(
                        help_text="Numéro de version (v1.0, v2.0…)", max_length=16
                    ),
                ),
                ("date", models.DateField()),
                (
                    "auteur",
                    models.CharField(help_text="Auteur (nom complet)", max_length=255),
                ),
                ("commentaire", models.TextField(help_text="Commentaire de version")),
                (
                    "facteurs",
                    models.PositiveIntegerField(
                        default=0, help_text="Nombre de facteurs SWOT + PESTEL figés"
                    ),
                ),
                (
                    "enjeux",
                    models.PositiveIntegerField(
                        default=0, help_text="Nombre d'enjeux figés"
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "version de l'analyse du contexte",
                "verbose_name_plural": "versions de l'analyse du contexte",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="contexte_analyseversion_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Applicabilite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "norme",
                    models.CharField(
                        choices=[
                            ("9001", "ISO 9001"),
                            ("14001", "ISO 14001"),
                            ("45001", "ISO 45001"),
                            ("27001", "ISO 27001"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "article",
                    models.CharField(help_text="Article / exigence", max_length=255),
                ),
                (
                    "exclu",
                    models.CharField(
                        choices=[("Oui", "Oui"), ("Non", "Non")],
                        default="Non",
                        max_length=4,
                    ),
                ),
                ("justification", models.TextField()),
                ("commentaire", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "exigence normative",
                "verbose_name_plural": "applicabilité normative",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="contexte_applicabilite_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Axe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("code", models.CharField(help_text="Code (AX1…)", max_length=32)),
                (
                    "libelle",
                    models.CharField(
                        help_text="Orientation stratégique", max_length=255
                    ),
                ),
                (
                    "avancement",
                    models.PositiveSmallIntegerField(
                        help_text="Avancement de la mise en œuvre (%)",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "evaluation",
                    models.TextField(help_text="Évaluation de la mise en œuvre"),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "axe stratégique",
                "verbose_name_plural": "axes stratégiques",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"), name="contexte_axe_uid_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DomaineVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "version",
                    models.CharField(
                        help_text="Numéro de version (v1, v2…)", max_length=16
                    ),
                ),
                ("date", models.DateField()),
                (
                    "auteur",
                    models.CharField(help_text="Auteur (nom complet)", max_length=255),
                ),
                ("commentaire", models.TextField(help_text="Commentaire de version")),
                (
                    "facteurs",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre de facteurs SWOT + PESTEL",
                        null=True,
                    ),
                ),
                (
                    "enjeux",
                    models.PositiveIntegerField(
                        blank=True, help_text="Nombre d'enjeux", null=True
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "version du domaine d'application",
                "verbose_name_plural": "versions du domaine d'application",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="contexte_domaineversion_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Enjeu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "libelle",
                    models.CharField(help_text="Libellé de l'enjeu", max_length=255),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("Interne (SWOT)", "Interne"),
                            ("Externe (PESTEL)", "Externe"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        choices=[("Positif", "Positif"), ("Négatif", "Negatif")],
                        max_length=16,
                    ),
                ),
                (
                    "axes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Axes de la politique associés (id d'axes)",
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        blank=True,
                        help_text="Facteur SWOT ou PESTEL d'origine (id) — absent pour un enjeu saisi à la main",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("date", models.DateField(help_text="Date d'identification")),
                (
                    "statut",
                    models.CharField(
                        choices=[("Actif", "Actif"), ("Obsolète", "Obsolete")],
                        default="Actif",
                        max_length=16,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "enjeux",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"), name="contexte_enjeu_uid_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PartieInteressee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de la partie intéressée", max_length=255
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[("Interne", "Interne"), ("Externe", "Externe")],
                        max_length=16,
                    ),
                ),
                ("exigences", models.TextField(help_text="Exigences et attentes")),
                (
                    "pouvoir",
                    models.PositiveSmallIntegerField(
                        help_text="Pouvoir (1 à 5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "legitimite",
                    models.PositiveSmallIntegerField(
                        help_text="Légitimité (1 à 5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "urgence",
                    models.PositiveSmallIntegerField(
                        help_text="Urgence (1 à 5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("plan", models.TextField(help_text="Plan d'engagement")),
                (
                    "plan_mis_en_oeuvre",
                    models.BooleanField(
                        default=False, help_text="Plan d'engagement mis en œuvre"
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "partie intéressée",
                "verbose_name_plural": "parties intéressées",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="contexte_partieinteressee_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Pestel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("Politique", "Politique"),
                            ("Économique", "Economique"),
                            ("Socioculturel", "Socioculturel"),
                            ("Technologique", "Technologique"),
                            ("Environnemental", "Environnemental"),
                            ("Légal", "Legal"),
                        ],
                        help_text="Dimension PESTEL",
                        max_length=32,
                    ),
                ),
                ("facteur", models.CharField(help_text="Facteur", max_length=255)),
                (
                    "qualification",
                    models.CharField(
                        choices=[("Positif", "Positif"), ("Négatif", "Negatif")],
                        max_length=16,
                    ),
                ),
                (
                    "impact",
                    models.PositiveSmallIntegerField(
                        help_text="Impact (1 à 5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "facteur externe (PESTEL)",
                "verbose_name_plural": "facteurs externes (PESTEL)",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"), name="contexte_pestel_uid_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom du site (référencé par les activités)",
                        max_length=255,
                    ),
                ),
                ("adresse", models.CharField(max_length=255)),
                (
                    "activite",
                    models.CharField(help_text="Activité principale", max_length=255),
                ),
                (
                    "monnaie",
                    models.CharField(
                        choices=[
                            ("FCFA (XOF)", "Xof"),
                            ("EUR", "Eur"),
                            ("USD", "Usd"),
                            ("NGN (Naira)", "Ngn"),
                            ("GHS (Cedi)", "Ghs"),
                        ],
                        default="FCFA (XOF)",
                        max_length=16,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("Inclus", "Inclus"), ("Exclu", "Exclu")],
                        help_text="Inclus ou exclu du domaine",
                        max_length=8,
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        help_text="Justification (au moins 10 caractères)"
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "site",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"), name="contexte_site_uid_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Swot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "type",
                    models.CharField(
                        choices=[("Force", "Force"), ("Faiblesse", "Faiblesse")],
                        help_text="Type de facteur",
                        max_length=16,
                    ),
                ),
                (
                    "libelle",
                    models.CharField(help_text="Libellé du facteur", max_length=255),
                ),
                ("description", models.TextField(help_text="Description")),
                (
                    "impact",
                    models.PositiveSmallIntegerField(
                        help_text="Impact sur le SM (1 faible à 5 fort)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "facteur interne (SWOT)",
                "verbose_name_plural": "facteurs internes (SWOT)",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"), name="contexte_swot_uid_uniq"
                    )
                ],
            },
        ),
    ]
