# Generated by Django 5.2.17 on 2026-09-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexte", "0003_collections_module1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activite",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analyseversion",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="applicabilite",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="axe",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="domaineversion",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="enjeu",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="partieinteressee",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pestel",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="processus",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="site",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="swot",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
