/** Titres de page (PAGES[id].t de l'original), affichés dans le fil d'Ariane. Généré par scripts/extract-reference.mjs. */
export const PAGE_TITLES: Record<string, string> = {
  "dashboard": "Tableau de bord",
  "cover": "Couverture normative",
  "journal": "Journal d'audit",
  "users": "Utilisateurs et rôles",
  "settings": "Paramètres",
  "help": "Centre d'aide",
  "m1-enjeux": "1.1 Enjeux",
  "m1-parties": "1.2 Parties intéressées",
  "m1-domaine": "1.3 Domaine d'application",
  "m1-processus": "1.4 Cartographie des processus",
  "m2-engagement": "2.1 Engagement de la direction",
  "m2-politique": "2.2 Politique SM",
  "m2-roles": "2.3 Rôles et responsabilités",
  "m2-consultation": "2.4 Consultation et participation",
  "m3-objectifs": "3.1 Objectifs et actions",
  "m3-veille": "3.3 Veille réglementaire",
  "m3-risques": "3.4 Risques et opportunités",
  "m4-ressources": "4.1 Ressources",
  "m4-competences": "4.2 Compétences",
  "m4-communication": "4.3 Communication",
  "m5-ged": "5.1 Gestion électronique des documents",
  "m5-planif": "5.2 Planification opérationnelle",
  "m5-urgences": "5.3 Situations d'urgence",
  "m3-fiches": "3.2 Fiche de maîtrise opérationnelle",
  "m6-surveillance": "6.1 Surveillance et mesures",
  "m6-audits": "6.2 Audits",
  "m6-revues": "6.3 Revues",
  "m6-nc": "6.4 Non-conformités et actions correctives",
  "m6-registre": "6.5 Registre d'amélioration continue",
}
