# Generated by Django 5.2.17 on 2026-09-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "liste",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Compétences suivies (libellés)",
                    ),
                ),
                (
                    "requis",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Niveau requis (0 à 4) par compétence",
                    ),
                ),
                (
                    "collaborateurs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{nom, direction, niveaux}] — un niveau (0 à 4) par compétence",
                    ),
                ),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "matrice des compétences",
                "verbose_name_plural": "matrices des compétences",
            },
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Sensibilisation", "Sensibilisation"),
                            ("Communication", "Communication"),
                        ],
                        default="Sensibilisation",
                        max_length=32,
                    ),
                ),
                ("objectif", models.CharField(help_text="Objectif", max_length=255)),
                (
                    "qui_fait",
                    models.CharField(
                        blank=True, help_text="Qui fait (nom complet)", max_length=255
                    ),
                ),
                (
                    "portee",
                    models.CharField(
                        choices=[("Interne", "Interne"), ("Externe", "Externe")],
                        default="Interne",
                        max_length=16,
                    ),
                ),
                (
                    "cible",
                    models.CharField(
                        blank=True,
                        help_text="Cible (interne ou externe)",
                        max_length=255,
                    ),
                ),
                (
                    "moyen",
                    models.CharField(blank=True, help_text="Moyen", max_length=255),
                ),
                ("date", models.DateField(help_text="Date prévue (délai)")),
                (
                    "statut",
                    models.CharField(
                        choices=[("Pas fait", "Pas fait"), ("Fait", "Fait")],
                        default="Pas fait",
                        max_length=16,
                    ),
                ),
                (
                    "date_realisation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Date de réalisation effective (AAAA-MM-JJ) ou vide",
                        max_length=10,
                    ),
                ),
                (
                    "processus",
                    models.CharField(
                        blank=True, help_text="Processus associé (id)", max_length=32
                    ),
                ),
                (
                    "preuve",
                    models.CharField(
                        blank=True,
                        help_text="Preuve (nom du fichier) ou « — »",
                        max_length=255,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "action de communication",
                "verbose_name_plural": "plan de communication",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="support_communication_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                ("theme", models.CharField(help_text="Thème", max_length=255)),
                ("date", models.DateField(help_text="Date de la session")),
                (
                    "formateur",
                    models.CharField(
                        blank=True,
                        help_text="Formateur (interne ou organisme)",
                        max_length=255,
                    ),
                ),
                (
                    "participants",
                    models.CharField(
                        blank=True, help_text="Participants", max_length=255
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Planifiée", "Planifiée"),
                            ("Réalisée", "Réalisée"),
                            ("Reportée", "Reportée"),
                        ],
                        default="Planifiée",
                        max_length=16,
                    ),
                ),
                (
                    "evaluation_date",
                    models.DateField(help_text="Évaluation post-formation prévue le"),
                ),
                (
                    "evaluation_responsable",
                    models.CharField(
                        blank=True,
                        help_text="Responsable de l'évaluation (nom complet)",
                        max_length=255,
                    ),
                ),
                (
                    "resultat",
                    models.TextField(
                        blank=True,
                        help_text="Résultat de l'évaluation (Kirkpatrick 1 à 4) ou « — »",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "session de formation",
                "verbose_name_plural": "plan de formation",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="support_formation_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Ressource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "besoin",
                    models.CharField(help_text="Besoin exprimé", max_length=255),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Humaine", "Humaine"),
                            ("Matérielle", "Matérielle"),
                            ("Financière", "Financière"),
                            ("Infrastructure", "Infrastructure"),
                        ],
                        help_text="Nature de la ressource",
                        max_length=32,
                    ),
                ),
                (
                    "processus",
                    models.CharField(
                        blank=True, help_text="Processus concerné (id)", max_length=32
                    ),
                ),
                (
                    "disponible",
                    models.CharField(
                        blank=True,
                        help_text="Bilan : disponible actuellement",
                        max_length=255,
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, help_text="Justification du besoin"),
                ),
                (
                    "montant",
                    models.BigIntegerField(
                        default=0, help_text="Montant estimé (FCFA)"
                    ),
                ),
                (
                    "circuit",
                    models.CharField(
                        choices=[
                            ("RH", "RH"),
                            ("Finance", "Finance"),
                            ("Achats", "Achats"),
                        ],
                        help_text="Circuit de validation",
                        max_length=16,
                    ),
                ),
                (
                    "date_demandee",
                    models.DateField(help_text="Date de mise à disposition souhaitée"),
                ),
                (
                    "date_reelle",
                    models.CharField(
                        default="—",
                        help_text="Date réelle de mise à disposition (AAAA-MM-JJ) ou « — »",
                        max_length=10,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("Soumise", "Soumise"),
                            ("Validée", "Validée"),
                            ("Refusée", "Refusée"),
                            ("Mise à disposition", "Mise à disposition"),
                        ],
                        default="Brouillon",
                        max_length=32,
                    ),
                ),
                (
                    "demandeur",
                    models.CharField(
                        blank=True, help_text="Demandeur (nom complet)", max_length=255
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de ressource",
                "verbose_name_plural": "demandes de ressources",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="support_ressource_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Savoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "savoir",
                    models.CharField(help_text="Savoir critique", max_length=255),
                ),
                (
                    "detenteurs",
                    models.CharField(
                        blank=True,
                        help_text="Détenteurs actuels (noms, séparés par des virgules)",
                        max_length=500,
                    ),
                ),
                (
                    "couverture",
                    models.CharField(
                        blank=True,
                        help_text="Couverture (ex. « 1 détenteur »)",
                        max_length=64,
                    ),
                ),
                (
                    "criticite",
                    models.CharField(
                        choices=[("Critique", "Critique"), ("Couvert", "Couvert")],
                        help_text="Situation",
                        max_length=16,
                    ),
                ),
                (
                    "action",
                    models.TextField(
                        blank=True, help_text="Action du plan de formation thématique"
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "savoir critique",
                "verbose_name_plural": "savoirs critiques",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"), name="support_savoir_uid_uniq"
                    )
                ],
            },
        ),
    ]
