# Generated by Django 5.2.17 on 2026-09-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communication",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="formation",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ressource",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="savoir",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
