# Generated by Django 5.2.17 on 2026-09-26 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourcesNC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "valeurs",
                    models.JSONField(
                        blank=True, default=list, help_text="Libellés des sources"
                    ),
                ),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "sources des non-conformités",
                "verbose_name_plural": "sources des non-conformités",
            },
        ),
        migrations.CreateModel(
            name="StatsSurveillance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "mois",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Libellés des mois (Mar, Avr…)",
                    ),
                ),
                (
                    "incidents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Nombre d'incidents par mois",
                    ),
                ),
                (
                    "dysfonctionnements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Dysfonctionnements par mois",
                    ),
                ),
                (
                    "dechets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Déchets produits par mois (t)",
                    ),
                ),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "statistiques de surveillance",
                "verbose_name_plural": "statistiques de surveillance",
            },
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "ref",
                    models.CharField(
                        help_text="Référence (AUD-2026-01)", max_length=64
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "perimetre",
                    models.CharField(
                        blank=True,
                        help_text="Processus audité (id P01…)",
                        max_length=32,
                    ),
                ),
                (
                    "auditeur",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'auditeur (db.auditeurs)",
                        max_length=255,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Planifié", "Planifie"),
                            ("Plan diffusé", "Plan Diffuse"),
                            ("En cours", "En Cours"),
                            ("Rapport déposé", "Rapport Depose"),
                            ("Clôturé", "Cloture"),
                        ],
                        default="Planifié",
                        max_length=16,
                    ),
                ),
                (
                    "rapport",
                    models.CharField(
                        blank=True,
                        default="—",
                        help_text="Fichier du rapport ou « — »",
                        max_length=255,
                    ),
                ),
                (
                    "constats",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Constats [{type, description, processus}]",
                    ),
                ),
                (
                    "compte_rendu",
                    models.TextField(
                        blank=True,
                        help_text="Compte-rendu de la réunion de clôture",
                        null=True,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="performance_audit_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Auditeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de l'auditeur ou du cabinet", max_length=255
                    ),
                ),
                ("qualification", models.CharField(blank=True, max_length=255)),
                ("disponibilite", models.CharField(blank=True, max_length=255)),
                (
                    "independance",
                    models.CharField(
                        blank=True,
                        help_text="Restriction d'indépendance (« Ne peut pas auditer P02 »)",
                        max_length=255,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "auditeur",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="performance_auditeur_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Indicateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "kpi",
                    models.CharField(
                        help_text="Intitulé de l'indicateur", max_length=255
                    ),
                ),
                (
                    "objectif",
                    models.CharField(
                        blank=True,
                        default="—",
                        help_text="Code de l'objectif rattaché (OB-01…) ou « — »",
                        max_length=32,
                    ),
                ),
                ("cible", models.FloatField(help_text="Valeur cible")),
                (
                    "unite",
                    models.CharField(
                        blank=True,
                        help_text="Unité (%, m³/t…), vide si sans unité",
                        max_length=32,
                    ),
                ),
                (
                    "sens",
                    models.CharField(
                        choices=[
                            ("hausse", "Plus haut = mieux"),
                            ("baisse", "Plus bas = mieux"),
                        ],
                        default="hausse",
                        help_text="Sens d'amélioration",
                        max_length=8,
                    ),
                ),
                (
                    "valeur",
                    models.FloatField(
                        blank=True, help_text="Dernière valeur mesurée", null=True
                    ),
                ),
                (
                    "moyen",
                    models.CharField(
                        blank=True, help_text="Moyen de mesure", max_length=255
                    ),
                ),
                ("echeance", models.DateField(help_text="Échéance")),
                (
                    "processus",
                    models.CharField(
                        blank=True, help_text="Processus (id P01…)", max_length=32
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True,
                        help_text="Responsable (nom complet)",
                        max_length=255,
                    ),
                ),
                ("action", models.TextField(blank=True, help_text="Action associée")),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "indicateur",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="performance_indicateur_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NonConformite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        help_text="Référence (NC-2026-014), générée si absente",
                        max_length=64,
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("Non-conformité", "Non Conformite"),
                            ("Accident / incident", "Accident"),
                            ("Piste d'amélioration", "Amelioration"),
                            ("Observation", "Observation"),
                        ],
                        default="Non-conformité",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source (liste db.sourcesNC)",
                        max_length=128,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "type_acte",
                    models.CharField(
                        choices=[
                            ("Conformité", "Conformite"),
                            ("Dysfonctionnement", "Dysfonctionnement"),
                        ],
                        default="Conformité",
                        help_text="Type d'acte",
                        max_length=32,
                    ),
                ),
                (
                    "cause",
                    models.TextField(
                        blank=True,
                        help_text="Analyse des causes (5 Pourquoi / Ishikawa)",
                    ),
                ),
                (
                    "action",
                    models.TextField(
                        blank=True, help_text="Action corrective / acte / plan d'action"
                    ),
                ),
                (
                    "mise_en_oeuvre",
                    models.TextField(
                        blank=True, help_text="Mise en œuvre (accidents)", null=True
                    ),
                ),
                ("lieu", models.CharField(blank=True, max_length=255)),
                (
                    "processus",
                    models.CharField(
                        blank=True, help_text="Processus (id P01…)", max_length=32
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Déclarée", "Declaree"),
                            ("Validée pilote", "Validee Pilote"),
                            ("En traitement", "En Traitement"),
                            ("Clôturée", "Cloturee"),
                            ("Refusée", "Refusee"),
                        ],
                        default="Déclarée",
                        max_length=16,
                    ),
                ),
                (
                    "n1",
                    models.CharField(
                        choices=[
                            ("En attente", "En Attente"),
                            ("Validé", "Valide"),
                            ("Refusé", "Refuse"),
                        ],
                        default="En attente",
                        help_text="Validation par le pilote",
                        max_length=16,
                    ),
                ),
                (
                    "n2",
                    models.CharField(
                        choices=[
                            ("En attente", "En Attente"),
                            ("Approuvé", "Approuve"),
                            ("Refusé", "Refuse"),
                        ],
                        default="En attente",
                        help_text="Approbation par le responsable du système",
                        max_length=16,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "declarant",
                    models.CharField(
                        blank=True, help_text="Déclarant (nom complet)", max_length=255
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        blank=True,
                        help_text="Origine (AUD-2026-02, Terrain…)",
                        max_length=255,
                    ),
                ),
                (
                    "efficacite",
                    models.TextField(
                        blank=True,
                        help_text="Évaluation de l'efficacité à la clôture",
                        null=True,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "non-conformité",
                "verbose_name_plural": "non-conformités",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="performance_nonconformite_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Prestataire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("nom", models.CharField(max_length=255)),
                (
                    "categorie",
                    models.CharField(
                        choices=[("Critique", "Critique"), ("Classique", "Classique")],
                        default="Classique",
                        max_length=16,
                    ),
                ),
                ("debut", models.DateField(help_text="Début de la collaboration")),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("Trimestrielle", "Trimestrielle"),
                            ("Semestrielle", "Semestrielle"),
                            ("Annuelle", "Annuelle"),
                        ],
                        default="Annuelle",
                        help_text="Fréquence d'évaluation",
                        max_length=16,
                    ),
                ),
                ("champ", models.TextField(blank=True, help_text="Champ d'évaluation")),
                (
                    "processus",
                    models.CharField(
                        blank=True, help_text="Processus (id P01…)", max_length=32
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True,
                        help_text="Responsable de l'évaluation",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dernière évaluation {qualite, delai, securite, environnement}, notes de 1 à 5",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "intervenant externe",
                "verbose_name_plural": "intervenants externes",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="performance_prestataire_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistreEntree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "ref",
                    models.CharField(
                        help_text="Référence (RG-2026-031)", max_length=64
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Non-conformité", "Non Conformite"),
                            ("Incident", "Incident"),
                            ("Piste d'amélioration", "Amelioration"),
                            ("Observation", "Observation"),
                            ("Action d'audit", "Action Audit"),
                            ("Action de revue", "Action Revue"),
                            ("Action corrective", "Action Corrective"),
                            ("Risque réalisé", "Risque Realise"),
                        ],
                        max_length=32,
                    ),
                ),
                ("intitule", models.TextField()),
                (
                    "origine",
                    models.CharField(
                        blank=True,
                        help_text="Origine (Audit AUD-2026-02, Risque R07…)",
                        max_length=255,
                    ),
                ),
                (
                    "processus",
                    models.CharField(
                        blank=True, help_text="Processus (id P01…)", max_length=32
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("En cours", "En Cours"), ("Clôturé", "Cloture")],
                        default="En cours",
                        max_length=16,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "responsable",
                    models.CharField(
                        blank=True,
                        help_text="Responsable (nom complet)",
                        max_length=255,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrée du registre d'amélioration",
                "verbose_name_plural": "registre d'amélioration continue",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="performance_registreentree_uid_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Revue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("normes", models.JSONField(blank=True, default=list)),
                (
                    "ref",
                    models.CharField(help_text="Référence (RD-2026-S1)", max_length=64),
                ),
                ("date", models.DateField(help_text="Date de la réunion de pilotage")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Revue de direction semestrielle", "Semestrielle"),
                            ("Revue de direction annuelle", "Annuelle"),
                            ("Revue de processus", "Processus"),
                            ("Revue de sécurité de l'information", "Securite"),
                        ],
                        default="Revue de direction semestrielle",
                        max_length=64,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("Préparée", "Preparee"), ("Clôturée", "Cloturee")],
                        default="Préparée",
                        max_length=16,
                    ),
                ),
                ("participants", models.TextField(blank=True)),
                (
                    "ordre_du_jour",
                    models.JSONField(
                        blank=True, default=list, help_text="Points de l'ordre du jour"
                    ),
                ),
                (
                    "rapport_entree",
                    models.TextField(blank=True, help_text="Rapport d'entrée"),
                ),
                ("pv", models.TextField(blank=True, help_text="Procès-verbal")),
                (
                    "actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Plan d'action [{libelle, responsable, echeance, statut}]",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "revue",
                "ordering": ["position", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "uid"),
                        name="performance_revue_uid_uniq",
                    )
                ],
            },
        ),
    ]
