# Generated by Django 5.2.17 on 2026-09-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="auditeur",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="indicateur",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nonconformite",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="prestataire",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="registreentree",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="revue",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
